version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: pokuc/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media/

  frontend:
    env_file: .env
    image: pokuc/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    env_file: .env
    image: pokuc/foodgram_gateway
    ports:
      - "9090:80"
    volumes:
      - static:/staticfiles/
      - media:/app/media/
    depends_on:
      - frontend
      - backend
